### ISSUE TITLE
Unable to create images by following the community doc

### ISSUE THREAD

**Issue by alfhad** [Seagate/cortx#1384] opened 2022-01-13 14:30 UTC
I was trying to follow the [community doc](https://github.com/Seagate/cortx/blob/main/doc/community-build/docker/cortx-all/README.md)   but I am getting the following error while trying to build an image: 
```
[root@pokemon cortx-deploy]# ./build.sh -b http://192.168.16.135
Building cortx-all image from http://192.168.16.135
WARNING: The CREATED_DATE variable is not set. Defaulting to a blank string.
WARNING: Flag '--compress' is ignored when building with COMPOSE_DOCKER_CLI_BUILD=1
Building cortx-all
unknown flag: --iidfile
See 'docker build --help'.
ERROR: Service 'cortx-all' failed to build : Build failed
```

**Comment by r-wambui** [comment] 2022-01-17 15:01
Hi @alfhad I have not seen this issue before, I'll try to reproduce the image.

**Comment by r-wambui** [comment] 2022-01-17 20:23
@alfhad I'm able to build the image on my end. `cortx-all:2.0.0-0 2022-01-18 02:21:55 +0300 EAT`

The error you are having is related to the docker compose,  could you check the following link https://github.com/docker/compose/issues/8296, and let me know if this helps.

**Comment by alfhad** [comment] 2022-01-17 21:42
@r-wambui I took reference from the following link https://github.com/docker/compose/issues/8296 and seems the error was due to an older version of docker installed. I tried reinstalling docker to the latest version and it fixed the error, I was able to build the images successfully, Thanks!!

**Comment by r-wambui** [comment] 2022-01-18 09:20
@alfhad Great!, I'll therefore close this issue.

**Closed by r-wambui** 2022-01-18 09:20 UTC
Labels: Triage: DevAd, Rose

**Comment by cortx-admin** [comment] 2022-01-19 16:53
> John Bent commented in Jira Server:

Fixed in GitHub

**Comment by cortx-admin** [comment] 2022-01-19 16:53
> John Bent commented in Jira Server:

Closed in github

**Comment by cortx-admin** [comment] 2022-01-20 10:18
> Rose Wambui commented in Jira Server:

Testing Jira access,

**Comment by cortx-admin** [comment] 2022-01-20 10:18
> Rose Wambui commented in Jira Server:

The issue is already resolved, I'm using it to test my access rights to Jira

**Comment by cortx-admin** [comment] 2022-01-20 10:18
> Rose Wambui commented in Jira Server:

Already resolved

**Comment by cortx-admin** [comment] 2022-01-20 10:18
> Rose Wambui commented in Jira Server:

Resolve
