### ISSUE TITLE
Problem with 'Deploy CORTX Build Stack' process.

### ISSUE THREAD

**Issue by paulq11** [Seagate/cortx#1282] opened 2021-10-04 18:05 UTC
The instructions for 'Deploy CORTX Build Stack' fail for me at Step 11, 'cortx_setup node initialize'. 
I am on a VMWare workstation VM with centos 7.9.2009. The build goes perfectly, and the deploy sequence works until 11. The console output is attached as 'console.output.txt'
[console.output.txt](https://github.com/Seagate/cortx/files/7280202/console.output.txt)
.
The logs in /var/log/seagate/provisioner that seem to correspond are attached as well.
[nodecli.log](https://github.com/Seagate/cortx/files/7280240/nodecli.log)
[install.log](https://github.com/Seagate/cortx/files/7280241/install.log)
[salt_master.log](https://github.com/Seagate/cortx/files/7280243/salt_master.log)
[salt_minion.log](https://github.com/Seagate/cortx/files/7280244/salt_minion.log)

@shailesh-vaidya @justinzw @r-wambui @mukul-seagate11 @johnbent 

By the way - I am also testing on a VMWare Fusion hosted from a Mac - using the same guest configuration, and I get failures in the same step.

**Comment by johnbent** [comment] 2021-10-04 18:08
Thanks @paulq11! As @r-wambui is the DA assigned to parent, Rose, can you please attempt to reproduce this? 

[https://seagate-systems.atlassian.net/wiki/spaces/PRIVATECOR/pages/127894381/Gatekeepers+Gatekeeping+and+Community+Triage+and+Support](https://seagate-systems.atlassian.net/wiki/spaces/PRIVATECOR/pages/127894381/Gatekeepers+Gatekeeping+and+Community+Triage+and+Support)

**Comment by r-wambui** [comment] 2021-10-04 18:23
@johnbent Sure.

@paulq11 I'll test the build on my end and keep you updated.

**Comment by johnbent** [comment] 2021-10-04 18:48
Hey @paulq11 , I just merged a PR for this set of instructions: #1247 . Maybe that fixed it?

**Comment by paulq11** [comment] 2021-10-04 19:17
Great -
Checking it now on both machines.

Paul



Seagate Internal

**Comment by johnbent** [comment] 2021-10-04 20:33
@paulq11 , are you just trying to replicate the FDMI sample app? If so, I would suggest just building and deploying motr instead of building and deploying the full stack. It's MUCH MUCH easier. So, if you just want to work with FDMI, I think all you need to do is the following:

1. https://github.com/Seagate/cortx-motr/blob/main/doc/Quick-Start-Guide.rst
2. https://github.com/Seagate/cortx-motr/blob/main/fdmi/plugins/motr-fdmi-app.md

I would be a bit disappointed because the pressure you are putting on the deployment of the full stack is also very useful! But, more importantly to me, I just want to enable you and @rupasree-roy to work on the ransomware project and I think this could be a significant simplification for you.

**Comment by johnbent** [comment] 2021-10-04 22:04
@r-wambui , I talked to Paul and this remains a priority. He does need the full stack so thanks for helping him here!

**Comment by paulq11** [comment] 2021-10-04 22:21
The test with the #1247 tag did not work on the Mac VM... nodecli attached. Looks as if it is trying to reference eth0 -- and on this vm we have only ens33, ens34, and ens35

[nodecli.log.mac.txt.log](https://github.com/Seagate/cortx/files/7281629/nodecli.log.mac.txt.log)
.

**Comment by paulq11** [comment] 2021-10-05 01:27
And it didn't work as well on the windows hosted centos7.9 guest either. Same step, 11. Nodecli.log attached
[nodecli.win.log.txt](https://github.com/Seagate/cortx/files/7282169/nodecli.win.log.txt)
.

**Comment by mukul-seagate11** [comment] 2021-10-06 03:50
> The test with the #1247 tag did not work on the Mac VM... nodecli attached. Looks as if it is trying to reference eth0 -- and on this vm we have only ens33, ens34, and ens35
> 
> [nodecli.log.mac.txt.log](https://github.com/Seagate/cortx/files/7281629/nodecli.log.mac.txt.log) .

@paulq11, the error in nodecli log is due to, your interfaces are different so you have to select the same according as,

```
2021-10-02 16:54:43 nodecli ERROR cortx_setup command Failed: salt command failed, reason { 
	srvnode-1: ["Rendering SLS 'base:components.system.config.hosts' failed: Jinja variable 'dict object' has no attribute 'ens35'"], 
```

Which is clearly mentioned in step 7 as NOTE as,

![image](https://user-images.githubusercontent.com/65269273/136137826-b7373f37-f30a-467a-8209-518e585d3168.png)

**Comment by paulq11** [comment] 2021-10-06 12:53
Hi @mukul-seagate11 
My interfaces are set on that VM to ens33, ens34, and ens35. Attached is a screen shot
Thank you for looking in to this !

![mac_cortx_vm_net_interfaces jpg](https://user-images.githubusercontent.com/8881528/136205901-a4ee26d3-cc30-4570-bac4-f6982b6ecd5a.png)

**Comment by paulq11** [comment] 2021-10-06 16:20
Here's an update to the windows host (vmware workstation 16.1.2) with centos 7.9.2009 guest - completely fresh install this morning - build was fine, deploy failed at step 5 "sh install.sh -t http://${LOCAL_IP}/0"  with a message saying it could not stat a file (see screen shot). Install log does not have errors.
![step5_snip](https://user-images.githubusercontent.com/8881528/136243661-e4306111-0851-446f-8f68-575310a852ca.PNG)
 
[install.winhost.centos79.log](https://github.com/Seagate/cortx/files/7295626/install.winhost.centos79.log)

**Comment by mukul-seagate11** [comment] 2021-10-07 08:26
@paulq11, yes this error has already been identified & reported to the respective component as to fix the same.

**Comment by johnbent** [comment] 2021-10-08 23:41
Just an update for Seagate folks who want to see the progress on fixing this bug: [https://jts.seagate.com/browse/EOS-25301](https://jts.seagate.com/browse/EOS-25301) FYI @paulq11 and @r-wambui

**Comment by paulq11** [comment] 2021-10-09 01:58
I just tried a build based on #1302 of https://github.com/Seagate/cortx/blob/main/doc/community-build/ProvisionReleaseBuild.md and got a bit further. Fail on step 12 this time - the cortx_setup node finalize. Here 
is the last output..

[root@deploy-test scripts]# cortx_setup storage config --cvg dgB01 --data-devices /dev/sdb1,/dev/sdb2,/dev/sdb3 --metadata-devices /dev/sdb4
[root@deploy-test scripts]# cortx_setup storage config --cvg dgA01 --data-devices /dev/sdc1,/dev/sdc2,/dev/sdc3 --metadata-devices /dev/sdc4
[root@deploy-test scripts]# cortx_setup security config --certificate /opt/seagate/cortx/provisioner/srv/components/misc_pkgs/ssl_certs/files/stx.pem
[root@deploy-test scripts]# cortx_setup node initialize
[root@deploy-test scripts]# cortx_setup node finalize
cortx_setup command Failed: provisioner/common_config/resource_map_path resource is not configured

The environment is a KVM host with all specs as per the build instructions. If you need any log 
material let me know.

**Comment by mukul-seagate11** [comment] 2021-10-12 08:04
@paulq11, yes as its not merged yet so in the meantime you can follow similar updated instructions in https://github.com/mukul-seagate11/cortx-1/blob/main/doc/community-build/ProvisionReleaseBuild.md

**Comment by mukul-seagate11** [comment] 2021-10-13 11:57
@paulq11, Have you tested again on fresh VM?

**Closed** 2021-10-13 15:21 UTC
Labels: Triage: DevAd

**Comment by mukul-seagate11** [comment] 2021-10-14 05:21
@paulq11, yes this error is actually fixed in 2.0.0-527 TAG & the same has been updated in https://github.com/mukul-seagate11/cortx-1/blob/main/doc/community-build/Generate-Cortx-Build-Stack.md

Feel free to open a new issue If you still observe the same issue in 527

**Comment by paulq11** [comment] 2021-10-14 14:41
Great, Thanks Mukul !

Will verify today on all my machines.

Paul



Seagate Internal

**Comment by paulq11** [comment] 2021-10-14 18:20
Hi Rose,
Thanks. I am seeing issues in the initial make clean build step (step 4) in tag 2.0.0-257.  This
Here's my log.

***@***.*** cortx-s3server]# docker run --rm -v /root/cortx:/cortx-workspace ghcr.io/seagate/cortx-build:centos-7.9.2009 make checkout BRANCH=2.0.0-527 > /dev/null 2>&1
cd ~/cortx/cortx-s3server; git checkout 2.0.0-527
***@***.*** cortx-s3server]# cd ~/cortx/cortx-s3server; git checkout 2.0.0-527
HEAD is now at 41f54a5... Updated S3 QSG and also added Tested section (#1374)
***@***.*** cortx-s3server]# mkdir -p /var/artifacts/ && mkdir -p /mnt/cortx/{components,dependencies,scripts}
***@***.*** cortx-s3server]# docker run --rm -v /var/artifacts:/var/artifacts -v /root/cortx:/cortx-workspace ghcr.io/seagate/cortx-build:centos-7.9.2009 make clean build
rm -rf "/root/rpmbuild/"
rm -rf "/var/artifacts/0"
mkdir -p "/var/artifacts/0/cortx_iso"
mkdir: cannot create directory '/var/artifacts/0': Permission denied
make: *** [clean] Error 1
***@***.*** cortx-s3server]#



Seagate Internal

**Comment by paulq11** [comment] 2021-10-16 01:12
Hi Rose,
I found the issue with my previous build. As I said it was selinux being on. I did run the commands
In the pre-req doc which turns selinix off ... however I did not reboot.
Fixed that and I am at what I think is the same errors you are getting. Here is the log.

***@***.*** scripts]# cortx_setup node initialize
***@***.*** scripts]# cortx_setup node finalize --force
One or more node validation(s) failed: provisioner/common_config/resource_map_path resource is not configured.
Forcibly creating users..
Field users created. Check logs for more details on the validations error..
***@***.*** scripts]#




Seagate Internal

**Comment by cortx-admin** [comment] 2021-12-02 10:27
> Mukul Malhotra commented in Jira Server:

request closed as part of triage process

**Comment by cortx-admin** [comment] 2021-12-02 10:27
> Mukul Malhotra commented in Jira Server:

request closed as part of triage process

**Comment by cortx-admin** [comment] 2021-12-02 10:27
> Mukul Malhotra commented in Jira Server:

.
