### ISSUE TITLE
Cannot register an account on CORXT GUI- while building CORTX From Source.

### ISSUE THREAD

**Issue by r-wambui** [Seagate/cortx#1188] opened 2021-08-24 20:13 UTC
I managed to build CORTX from the source for a single node; however, I cannot register an account on the GUI. 
<img width="622" alt="Screenshot 2021-08-24 at 21 18 20" src="https://user-images.githubusercontent.com/27200863/130682906-7046bf83-a1df-4636-940a-9f89f4a58bde.png">

<img width="586" alt="Screenshot 2021-08-24 at 21 18 25" src="https://user-images.githubusercontent.com/27200863/130682926-781ebb14-b054-4fcd-8a75-9d26eae33c4f.png">

When you click on get started, on is redirected to the login route.
<img width="677" alt="Screenshot 2021-08-24 at 21 18 39" src="https://user-images.githubusercontent.com/27200863/130683076-7258ff2a-d3ea-448b-a9dd-bee8d7290149.png">

I'm looking at some of the latest commits on the cortx-management portal: https://github.com/Seagate/cortx-management-portal/commit/c27113f83f1c58868cabfd574a21a8b105f49ae1 seems the `adminuser` route has been removed.

Does this mean we do not need to create an admin a/c. If so, what credentials do we use for the login?

**Comment by mukul-seagate11** [comment] 2021-08-25 14:47
@r-wambui, please refer the Preboarding section [5] in https://github.com/Seagate/cortx/blob/main/doc/Preboarding_and_Onboarding.rst#Preboarding for more details.

![image](https://user-images.githubusercontent.com/65269273/130812666-ec73ae1e-b36d-4a4e-b56f-0ea9a747ccbf.png)

**Comment by r-wambui** [comment] 2021-08-25 16:16
@mukul-seagate11 Thanks for the link. However, I cannot create an account, after step 4 when you accept the terms and conditions, step 5 is skipped and redirected to login. There's no option to create a user.

I shared a link of a commit where the adminuser route seems to have been removed and replaced with login.

**Comment by hessio** [comment] 2021-08-30 15:29
I see you made this commit **@azam93 should this cause this issue that @r-wambui is seeing it seems that it should be the cause of this issue right?**

**How does one create an account now? Is there something we are missing here?** 

**cc** @kupranay

**Comment by r-wambui** [comment] 2021-08-30 15:34
@hessio I reached out to @azam93; the designs have slightly changed; they have replaced registering an A/c with a default username and password; once you log in, you are requested to change the password. 

Should we include this in the documentation for clarity?

**Comment by hessio** [comment] 2021-08-30 15:35
Oh please do this if you don't mind, thanks @r-wambui

**Comment by mukul-seagate11** [comment] 2021-09-15 14:38
Issue has been fixed in PR#1191

**Closed** 2021-09-16 19:16 UTC
