### ISSUE TITLE
A partner can't install the OVA on ESXi 6.5

### ISSUE THREAD

**Issue by gregnsk** [Seagate/cortx#417] opened 2020-10-21 04:05 UTC
From the partner:
---------------
I'm unable to run this on ESX.  It's been exported as a hardware version 17, so only the latest ESXi 7.0 or Fusion/Workstation can run it.  We run ESXi 6.5 in the lab. I tried to get it to import my messing with the ovf file a bit, but it doesn't look like I'm going to be able to get this to deploy.
---------------

**Comment by voyager529** [comment] 2020-10-24 04:15
Not a fix, but a workaround I was able to get working successfully...

1. Open the OVF in 7-zip.
2. Extract the OVA file.
3. Open the OVA in a text editor.
4. Find the string "vmx-17" and replace it with "vmx-10".
5. Save/Close text editor.
6. Add the edited OVA back into the OVF using 7-zip.
7. Delete the .mf file in the OVF.
8. Deploy to ESXi Host.

**Comment by korenlev** [comment] 2020-10-26 16:47
verified voyager529 suggestion on vsphere 6.5  - works

**Comment by mukul-seagate11** [comment] 2020-11-26 12:51
@VenkyOS, can you please document this?

**Comment by VenkyOS** [comment] 2020-11-27 11:00
@mukul-seagate11 - The description provided by voyager529 was documented in the below mentioned file. Hope, this should suffice. Please refer the **VMware ESX** section.

https://github.com/Seagate/cortx/blob/main/doc/Importing_OVA_File.rst

**Comment by mukul-seagate11** [comment] 2020-11-30 12:11
As the issue is addressed in https://github.com/Seagate/cortx/blob/main/doc/Importing_OVA_File.rst so closing the issue accordingly

**Closed by mukul-seagate11** 2020-11-30 12:11 UTC
Labels: bug
