### ISSUE TITLE
s3authserver service does not start when restarting CORTX

### ISSUE THREAD

**Issue by justinzw** [Seagate/cortx#415] opened 2020-10-21 02:04 UTC
Steps: Follow proper shutdown and restart of CORTX.
https://github.com/Seagate/cortx/blob/main/doc/CORTX_on_Open_Virtual_Appliance.rst

Issue: s3authserver service did not start

![image](https://user-images.githubusercontent.com/950172/96663965-a55d0380-1306-11eb-8496-a4b8e161ae68.png)

**Comment by mukul-seagate11** [comment] 2020-10-23 05:05
@justinzw, yes I too observed the same as,

[root@myvm ~]# systemctl is-active s3authserver
failed
[root@myvm ~]# hctl status
Cluster is not running.

**Comment by korenlev** [comment] 2020-10-26 16:46
hi friends,

this workaround has been working for me (3 files)  :

cat /etc/systemd/system/cortx_start.service 

[Unit]
Description=cortx hctl start
After=network.target

[Service]
Type=idle
RemainAfterExit=yes
ExecStart=/var/tmp/cortx_start
TimeoutStartSec=30

[Install]
WantedBy=default.target

[root@koren-cortx ~]# cat /var/tmp/cortx_start 

#!/bin/bash
hctl start
sleep 10s
/var/tmp/services-run-cmd start

[root@koren-cortx ~]# cat /var/tmp/services-run-cmd 

systemctl $1 rabbitmq-server
systemctl $1 elasticsearch
systemctl $1 haproxy
systemctl $1 s3authserver
systemctl $1 sspl-ll
systemctl $1 csm_agent
systemctl $1 csm_web

**Comment by sachitanands** [comment] 2020-10-30 04:19
Issue was s3authserver was trying to start before its dependent service (slapd) hence s3authserver was failing with LDAPConnectionException error after reboot.
Expected behavior is dependent service should start first and then s3authserver should start.
We are updating our OVA documentation to provide the correct steps to start these services in sequence.
PR: https://github.com/Seagate/cortx/pull/445

**Comment by sachitanands** [comment] 2020-11-03 04:31
Hi @justinzw @mukul-seagate11 since we have merged this PR with required changes, Can we close this issue?

**Comment by mukul-seagate11** [comment] 2020-11-03 05:03
Closing the PR as the issues has already been taken care & addressed in doc

**Comment by korenlev** [comment] 2020-11-16 17:28
guys, https://github.com/Seagate/cortx/pull/445 is a good solution/doc for a proper manual shutdown and restart, however users might expect VM restart to work automatically without ever touching any CLI...
where do i contribute my 2 scripts above to be included (if approved) in the next OVA release ?

**Comment by Saumya-Sunder** [comment] 2020-11-17 13:20
reopening the ticket and tagging Justin and John.

**Comment by mukul-seagate11** [comment] 2020-11-26 12:56
This discussion is already been discussed in https://github.com/Seagate/cortx/discussions/473 so closing the issue

**Closed** 2020-11-26 12:57 UTC
Labels: bug
