### ISSUE TITLE
cortx-manager build.sh failure

### ISSUE THREAD

**Issue by korenlev** [Seagate/cortx#424] opened 2020-10-22 13:30 UTC
per:
https://github.com/Seagate/cortx-manager/blob/main/CORTXManagerQuickstartGuide.md#12-Install-Cortx-Manager
sudo cicd/build.sh results:

failure: repodata/repomd.xml from cortx_commons: [Errno 256] No more mirrors to try.
http://cortx-storage.colo.seagate.com/releases/cortx/uploads/centos/centos-7.7.1908/repodata/repomd.xml: [Errno 14] curl#6 - "Could not resolve host: cortx-storage.colo.seagate.com; Unknown error

(tried from israel:  cortx-storage.colo.seagate.com: Name or service not known)

**Comment by justinzw** [comment] 2020-10-29 04:03
This is because it is pointing to an internal resource to Seagate. @shailesh-vaidya  will investigate. Thank you for reporting.

**Comment by shailesh-vaidya** [comment] 2020-11-05 12:26
Hi @korenlev Sorry for delayed response on this. I could not reproduce this issue locally yet. From above error, issue is due to yum repo with `http://cortx-storage.colo.seagate.com/releases/cortx/uploads/centos/centos-7.7.1908/` url. 

Can you please follow below steps,

- Identify repo name for `http://cortx-storage.colo.seagate.com/releases/cortx/uploads/centos/centos-7.7.1908/` URL

` yum repolist -v enabled | grep "http://cortx-storage.colo.seagate.com/releases/cortx/uploads/centos/centos-7.7.1908"  -B8 | grep repo-id -i | cut -d":" -f2
`
e.g. 
```
[root@102bcbf294c9 /]#  yum repolist -v enabled | grep "http://cortx-storage.colo.seagate.com/releases/cortx/uploads/centos/centos-7.7.1908"  -B8 | grep repo-id -i | cut -d":" -f2
 cortx-uploads
[root@102bcbf294c9 /]#
```
- Above command will give repo name. Disable that repo. 
 `yum-config-manager --disable cortx-uploads`

- After that please continue with `sudo cicd/build.sh`

Let me know how this works. Meanwhile I will continue to investigate this further.

**Comment by Saumya-Sunder** [comment] 2020-11-12 16:46
@shailesh-vaidya do I need to document this?

**Comment by johnbent** [comment] 2020-11-12 16:52
@Saumya-Sunder , please try to follow the the cortx-manager quick start guide and see if it works for you outside of the Seagate environment.  If not, do the above instructions from Shailesh help to fix?  If so, please do update the documentation so it works for people outside Seagate?

**Comment by mukul-seagate11** [comment] 2020-11-26 12:49
@Saumya-Sunder, can you please update on this?

**Comment by Saumya-Sunder** [comment] 2020-11-26 14:08
I will go through the document with @kupranay tomorrow, once it is fixed, I will test it out.

**Comment by mukul-seagate11** [comment] 2020-12-09 12:24
@Saumya-Sunder, please update if you are done with testing?

**Comment by Saumya-Sunder** [comment] 2020-12-09 13:17
This will take time, as I had to destroy my current vm and I will test the S3 by itself on Friday. Also, @nileshgovande is looped in, any issues I need to let him know the errors.

**Comment by mukul-seagate11** [comment] 2020-12-21 03:57
@Saumya-Sunder, please update, have you reached to S3 team to get the issue resolved

**Comment by mukul-seagate11** [comment] 2020-12-28 08:15
@Saumya-Sunder, please update & close accordingly

**Comment by Saumya-Sunder** [comment] 2020-12-28 08:17
Tested on VM Workstation Pro 16, script works fine for me.

**Comment by johnbent** [comment] 2020-12-28 19:23
@Saumya-Sunder , did you test from outside the Seagate network?  The reason it failed for @korenlev is because it tried to access an internal Seagate file: http://cortx-storage.colo.seagate.com/releases/cortx/uploads/centos/centos-7.7.1908/repodata/repomd.xml.

So, from the system where you did the testing, can you please try to just directly access this URL in your browser?  I just did and I can see it:
![image](https://user-images.githubusercontent.com/2047294/103238281-6e5b2d80-4907-11eb-9bce-5fd6143484b8.png)

So you need to somehow get on a system that is outside of the Seagate network which you can verify by trying and failing to access this link.  Once you have confirmed that you are on an external system, then can you try to reproduce this?

Does this make sense?

**Comment by Saumya-Sunder** [comment] 2020-12-28 19:30
Hey @johnbent, so you mean, I do not get on Citrix or use Seagate VMs and then try?

**Comment by johnbent** [comment] 2020-12-28 19:36
Yes, that is what I mean.
________________________________

**Comment by mukul-seagate11** [comment] 2021-01-04 03:56
@Saumya-Sunder, kindly take care as per suggested by John?

**Comment by mukul-seagate11** [comment] 2021-01-15 03:56
@Saumya-Sunder, please take this forward

**Comment by shailesh-vaidya** [comment] 2021-02-01 04:22
@Saumya-Sunder Can we conclude on this. Let me know if anything needed from my side.

**Comment by mukul-seagate11** [comment] 2021-06-30 14:47
As there is no update so closing the issue, please feel free to reopen if encounter any issue

**Closed by mukul-seagate11** 2021-06-30 14:47 UTC
Labels: bug, needs-attention
