### ISSUE TITLE
first preboarding procedure

### ISSUE THREAD

**Issue by wow123yf** [Seagate/cortx#1117] opened 2021-07-15 07:03 UTC
HI  .   I used CORTX for the first time  
when  i   first use the preboarding procedure  . i  get  it . My browser is Firefox   . 
![image](https://user-images.githubusercontent.com/30836989/125743262-7b493db7-9345-4193-a427-dd0806ca165f.png)

hctl status  is ok
s3authserver , haproxy  is  running

Looking forward to your reply

**Comment by justinzw** [comment] 2021-07-15 23:44
@wow123yf  Thank you for reporting this and I'm sorry you are running into issues. I'll work with you to solve this issue.

Could you tell me more about your setup?

Are you running this on VMware Workstation and is 192.168.11.232 the management IP?

**Comment by wow123yf** [comment] 2021-07-16 03:20
Thank you for your reply  。  
Virtualize is vmware vsphere 6.7   .    
192.168.11.232 is my  ens33 - Public data IP  . This  IP assigned through DHCP   .
if  i  use  ens32 - Management IP.  I can't connect the web page . I'm sure the IP is communicable .

**Comment by justinzw** [comment] 2021-07-16 17:43
ok, thank you for reporting this. It seems to be a firewall/networking issue. 

Which OVA are you using? 

Could you run this: ` systemctl stop firewalld` as root and see whether you can connect?

**Comment by 1156564544** [comment] 2021-07-18 06:03
I have an issue exactly like you. I can't connect the web page if I use ens32 - Management IP. If I use ens33 - Public IP, I opened a webpage just like you. Did you solve this problem?

**Comment by wow123yf** [comment] 2021-07-19 01:33
> ok, thank you for reporting this. It seems to be a firewall/networking issue.
> 
> Which OVA are you using?
> 
> Could you run this: ` systemctl stop firewalld` as root and see whether you can connect?

OVA is  1.0.4 
i stop firewalld  .  But the trouble is still there .
I tried installing Firefox local .  access a website for 127.0.0.1 . But the trouble is still there .

**Comment by mukul-seagate11** [comment] 2021-07-19 05:56
We don't have to stop the firewalld, seems some networking issue at your end, what network adaptors you had configured for your VM in VMware?

**Comment by wow123yf** [comment] 2021-07-19 07:48
network adaptors is  E1000      
ens32 - Management IP and ens33 - Public IP  both addresses are retrieved from DHCP server .
The network both can be pinging
And  i use local Firefox with CortX still failed

**Comment by justinzw** [comment] 2021-07-19 19:16
@wow123yf and @1156564544 it looks like the management service may not be running or there might be a networking issue like @mukul-seagate11 suggested.

2 things:

1) Can you run these commands?

`systemctl status rabbitmq-server`
`systemctl status elasticsearch`
`systemctl status haproxy`
`systemctl status s3authserver`
`systemctl status sspl-ll`
`systemctl status csm_agent`
`systemctl status csm_web`
`systemctl status hare-consul-agent`

you should see something like this for each time you run the command:
![image](https://user-images.githubusercontent.com/950172/126214501-f2ef7029-4728-4ea9-85e7-1dc5bd1c6301.png)

2) Can we setup a time today or tomorrow so that I can jump on a live session with you to debug this? I'll have to go through your networking configuration together with you.

You can either contact me on slack or e-mail me justin.woo@seagate.com

**Comment by wow123yf** [comment] 2021-07-20 03:41
The above services are active.
I have reserved   jump on a live session with you . 
debug this together

**Comment by justinzw** [comment] 2021-07-21 16:11
Thanks @wow123yf  for jumping on the call. The issue was resolved by appending port 28100 to the URL.

For NFS we don't have any immediate roadmap plans but we have most of the code ready and in github, we just need some testing and a bit more development.

**Comment by justinzw** [comment] 2021-07-21 16:12
Feel free to reopen/ping me if you have any further issues.

**Closed by justinzw** 2021-07-21 16:11 UTC

**Comment by johnbent** [comment] 2021-07-21 16:20
@justinzw , do we need to add something about appending port 28100 to the documents?

**Comment by justinzw** [comment] 2021-07-21 16:35
Good point and I'm investigating. The issue is that some OVAs versions do and some don't. I'll need to check which one does and which one doesn't and add it to the appropriate doc.
