### ISSUE TITLE
Cortx 2.0.0 OVA slow download

### ISSUE THREAD

**Issue by hseow-seagate** [Seagate/cortx#1214] opened 2021-09-19 06:21 UTC
I am able to download Cortx 1.0.4 from GitHub Release considerably much faster than Cortx 2.0.0 OVA (from cortx aws?).
Are there better mirrors or links for the new release?

_Note: Slow download also means it's easier to fail from interruption._

![image](https://user-images.githubusercontent.com/39552540/133917552-3f370105-b3f9-49a5-a4ac-fb97915a441e.png)

**Comment by hessio** [comment] 2021-09-20 13:36
Hi @mukul-seagate11 do you know if there is a faster way to download this?

**Comment by hessio** [comment] 2021-09-20 13:36
Hi @mukul-seagate11 do you know if there is a faster way to download this?

**Comment by mukul-seagate11** [comment] 2021-09-27 05:15
@hseow-seagate, this is expected behavior based on latency where 1.0.4 image is been downloaded from GitHub cloud and 2.0.0 is being downloaded from AWS cloud

**Comment by cortx-admin** [comment] 2021-09-27 05:33
> Mukul Malhotra commented in Jira Server:

@hseow-seagate, this is expected behavior based on latency where 1.0.4 image is been downloaded from GitHub cloud and 2.0.0 is being downloaded from AWS cloud

**Comment by cortx-admin** [comment] 2021-09-27 05:55
> Mukul Malhotra commented in Jira Server:

Closing this issue as expected behavior due to latency

**Comment by cortx-admin** [comment] 2021-09-27 05:55
> Mukul Malhotra commented in Jira Server:

Issue closed

**Comment by cortx-admin** [comment] 2021-09-27 06:16
> Mukul Malhotra commented in Jira Server:

Closed in GitHub issue

**Closed by cortx-admin** 2021-09-27 06:16 UTC
